name: release
on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: >
          docker build .
          --tag ghcr.io/dapplion/tcp-snooper:${{github.ref_name}}
          --tag ghcr.io/dapplion/tcp-snooper:latest

      # From https://gist.github.com/yokawasa/841b6db379aa68b2859846da84a9643c
      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - run: |
          docker push ghcr.io/dapplion/tcp-snooper:${{github.ref_name}}
          docker push ghcr.io/dapplion/tcp-snooper:latest
