on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: >
          docker build .
          --tag ghcr.io/dapplion/tcp-snooper:${{github.ref_name}}
          --tag ghcr.io/dapplion/tcp-snooper:latest
      - run: |
          docker push ghcr.io/dapplion/tcp-snooper:${{github.ref_name}}
          docker push ghcr.io/dapplion/tcp-snooper:latest
